version: "3.9"

services:
  database-service:
    image: postgres:latest
    container_name: obed-db
    restart: always # every time start-up will restart
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: obed-db
    ports:
      - "5432:5432"
