CREATE TABLE prefixes(
  title VARCHAR(50) UNIQUE PRIMARY KEY
);

INSERT INTO prefixes (title)
VALUES
    ('PROF_DR'),
		('PROF'),
		('ASSOC_PROF_DR'),
		('ASSOC_PROF'),
		('ASST_PROF_DR'),
		('ASST_PROF'),
		('DR'),
		('INSTRUCTOR');

CREATE TABLE roles(
  title VARCHAR(50) UNIQUE PRIMARY KEY
);

INSERT INTO roles (title)
VALUES
    ('ADMIN'),
		('TEACHER');

CREATE TABLE users(
  user_id SERIAL PRIMARY KEY,
  email VARCHAR(50) UNIQUE NOT NULL,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(60) NOT NULL,
  prefix VARCHAR(50) NOT NULL REFERENCES prefixes(title) ON UPDATE CASCADE ON DELETE CASCADE,
	firstname VARCHAR(50) NOT NULL,
	lastname VARCHAR(50) NOT NULL,
	g_auth_code VARCHAR(50),
	role VARCHAR(50) NOT NULL REFERENCES roles(title) ON UPDATE CASCADE ON DELETE CASCADE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);